-- DROP TABLE IF EXISTS food_logs;
-- DROP TABLE IF EXISTS daily_logs;
-- DROP TABLE IF EXISTS servings;
DROP TABLE IF EXISTS foods;
DROP TABLE IF EXISTS wweia_categories;
DROP TABLE IF EXISTS user_profile;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS aggregation_metadata;

DROP TYPE IF EXISTS SEX_TYPE;
DROP TYPE IF EXISTS GOAL_TYPE;
DROP TYPE IF EXISTS ACTIVITY_LEVEL_TYPE;
DROP TYPE IF EXISTS FOOD_SOURCE_TYPE;
